# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
baseurl: "" # the subpath of your site, e.g. /blog
environment: production
remote_data_prefix: "https://sdgdata.gov.uk/sdg-data"

reporting_status:
    description: | 
      
      Reporting status provides an overview of how much data the UK reports for Sustainable Development Goal global indicators.
      
      Disaggregation status provides an overview of how many indicators are disaggregated as mentioned in the indicator name. We also report many other disaggregations beyond these. For details about all disaggregations, see the [UK disaggregation report](https://sdgdata.gov.uk/sdg-data/disaggregations.html).
      
      Note: These percentages have been rounded. As a result, adding them together may not equal exactly 100%.

analytics:
  ga_prod: 'UA-108503280-1'
