# Site settings
title: U.K. Indicators For The Sustainable Development Goals
baseurl: "/sdg-indicators" # the subpath of your site, e.g. /blog
url: ""

# Build settings
markdown: kramdown




# Pages
collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /updates/:year/:month/:day/:title.html
  indicators:
    output: true
  goals:
    output: true
    

# This makes sure that all pages have a language.
defaults:
  -
    scope:
      path: ""
    values:
      language: "en"

plugins:
  - jekyll-remote-theme
  - jekyll-open-sdg-plugins

remote_theme: brockfanning/open-sdg@site-config-builder-schema-in-plugin
