accessible_charts: true
accessible_tabs: true
analytics:
  ga_prod: ''
breadcrumbs:
  goal: []
  indicator: []
  post: []
country:
  name: UK
  adjective: UK
create_config_forms:
  layout: config-builder
create_goals:
  layout: goal-by-target-vertical
create_indicators:
  layout: indicator
create_pages:
  - filename: ''
    folder: /
    layout: frontpage-alt
    title: 17 goals to transform our world
  - filename: ''
    folder: /goals
    layout: goals
    title: UK data for the Sustainable Development Goals
  - filename: ''
    folder: /reporting-status
    layout: reportingstatus
    title: Reporting Status
  - filename: indicators.json
    folder: /
    layout: indicator-json
    title: ''
  - filename: ''
    folder: /search
    layout: search
    title: Search results
custom_css:
  - /assets/css/custom.css
custom_js:
  - /assets/js/custom.js
data_edit_url: 'http://prose.io/#onsdigital/sdg-data/edit/develop/data/indicator_[id].csv'
date_formats:
  - type: standard
    language: en
    format: '%d %B %Y'
disclaimer:
  phase: ''
  message: ''
email_contacts:
  questions: sustainabledevelopment@ons.gov.uk
  suggestions: sustainabledevelopment@ons.gov.uk
  functional: sustainabledevelopment@ons.gov.uk
environment: staging
footer_language_toggle: none
footer_menu:
  - path: 'mailto:sustainabledevelopment@ons.gov.uk'
    translation_key: menu.contact_us
  - path: 'https://twitter.com/ONS'
    translation_key: general.twitter
  - path: /about/cookies-and-privacy/
    translation_key: menu.cookies
  - path: /accessibility-statement/
    translation_key: Accessibility statement
frontpage_cards:
  - title: Download all data
    content: ''
    include: components/download-all-data.html
    button_label: ''
    button_link: ''
    rule_color: ''
  - title: Publications
    content: >

      [SDGs in the UK: Progress on monitoring and reporting
      data](https://www.ons.gov.uk/economy/environmentalaccounts/articles/sustainabledevelopmentgoalstakingstockprogressandpossibilities/november2019)


      [UK SDG Voluntary National
      Review](https://www.gov.uk/government/publications/uks-voluntary-national-review-of-the-sustainable-development-goals)

      <br/><br/>

      <a href="./publications" aria-label="More publications">More
      publications...</a>
    include: ''
    button_label: ''
    button_link: ''
    rule_color: ''
  - title: Useful resources
    content: >

      [The Global Goals](https://www.globalgoals.org/)


      [Implementing the Sustainable Development
      Goals](https://www.gov.uk/government/publications/implementing-the-sustainable-development-goals/implementing-the-sustainable-development-goals--2)


      [UN Department of Economic and Social
      Affairs](https://sustainabledevelopment.un.org/)
    include: ''
    button_label: ''
    button_link: ''
    rule_color: ''
frontpage_goals_grid:
  title: UK data for the Sustainable Development Goals
  description: >-
    Click on each goal for UK Sustainable Development Goal global indicator
    data.
frontpage_heading: ''
frontpage_instructions: ''
frontpage_introduction_banner:
  title: 17 goals to transform our world
  description: >-
    <a
    href="https://www.un.org/sustainabledevelopment/sustainable-development-goals/">The
    Sustainable Development Goals (SDGs)</a> are a universal call to action to
    end poverty, protect the planet and improve the lives and prospects of
    everyone, everywhere. The 17 Goals were adopted by all UN Member States in
    2015, as part of the <a
    href="https://sustainabledevelopment.un.org/post2015/transformingourworld">2030
    Agenda for Sustainable Development</a>.
goal_image_base: 'https://open-sdg.github.io/sdg-translations/assets/img/goals'
goal_image_extension: svg
goals_page:
  title: UK data for the Sustainable Development Goals
  description: >-
    Click on each goal for UK Sustainable Development Goal global indicator
    data.
graph_color_set: default
graph_color_list: []
graph_color_number: 0
header_language_toggle: none
hide_empty_metadata: false
indicator_config_form:
  dropdowns: []
languages:
  - en
languages_public: []
map_layers:
  - subfolder: country
    label: Country
    min_zoom: 4
    max_zoom: 6
    staticBorders: true
  - subfolder: regions
    label: Regions
    min_zoom: 6
    max_zoom: 8
    staticBorders: true
  - subfolder: local_authorities
    label: Local Authorities
    min_zoom: 9
    max_zoom: 12
    staticBorders: true
map_options:
  minZoom: 4
  maxZoom: 0
  tileURL: >-
    https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}
  tileOptions:
    id: mapbox.light
    accessToken: >-
      pk.eyJ1IjoibHVjeWphbmVnd2lsbCIsImEiOiJjazAyZ2phaGMwajhzM2hxb2czZmdrZ2szIn0.tcj-n08CcU-7tKXFqB-WuQ
    attribution: >-
      <a href="https://www.mapbox.com">Mapbox</a> | <a
      href="http://geoportal.statistics.gov.uk/">ONS</a>
  colorRange: ''
  noValueColor: '#000000'
  styleNormal:
    weight: 0
    opacity: 0
    fillOpacity: 0
    color: '#000000'
    dashArray: ''
  styleHighlighted:
    weight: 0
    opacity: 0
    fillOpacity: 0
    color: '#000000'
    dashArray: ''
  styleStatic:
    weight: 0
    opacity: 0
    fillOpacity: 0
    color: '#000000'
    dashArray: ''
menu:
  - path: /goals
    translation_key: general.goals
  - path: /reporting-status/
    translation_key: menu.reporting_status
  - path: /about/
    translation_key: menu.about
  - path: /publications/
    translation_key: menu.publications
  - path: /faq/
    translation_key: menu.faq
  - path: /updates/
    translation_key: menu.updates
metadata_edit_url: 'http://prose.io/#onsdigital/sdg-data/edit/develop/meta/[id].md'
metadata_tabs: []
news:
  category_links: false
non_global_metadata: ''
remote_data_prefix: 'https://ONSdigital.github.io/sdg-data'
reporting_status:
  title: Reporting Status
  description: >-
    An overview of how much data the UK reports for Sustainable Development Goal
    global indicators.
search_index_boost: []
search_index_extra_fields:
  - indicator_available
  - graph_title
  - data_keywords
series_toggle: true
sharethis_property: ''
site_config_form:
  dropdowns: []
validate_indicator_config: false
validate_site_config: false
