# This is a basic workflow to help you get started with Actions

name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      
    - name: Setup Ruby, JRuby and TruffleRuby
      uses: ruby/setup-ruby@v1.38.0
      with:
        ruby-version: 2.7
        
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      
    - name: Build site
      run: |
        gem install jekyll bundler
        bundle install && bundle exec jekyll build

    - name: Install Pa11y
      run: npm install -g pa11y

    - name: Run accessibility tests
      run: |
        chmod +x ./scripts/accessibility-test/run_tests.sh
        ./scripts/accessibility-test/run_tests.sh
        pagePath="1" ./scripts/accessibility-test/run_tests.sh
        pagePath="about" ./scripts/accessibility-test/run_tests.sh
        pagePath="reporting-status" ./scripts/accessibility-test/run_tests.sh
        pagePath="faq" ./scripts/accessibility-test/run_tests.sh
        pagePath="updates" ./scripts/accessibility-test/run_tests.sh
        pagePath="updates" ./scripts/accessibility-test/run_tests.sh
        pagePath="accessibility-statement" ./scripts/accessibility-test/run_tests.sh