# This is a basic workflow to help you get started with Actions

name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      
    - name: Setup Ruby, JRuby and TruffleRuby
      uses: ruby/setup-ruby@v1.38.0
      with:
        ruby-version: 2.7
        
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      
    - name: Build site
      run: |
        gem install jekyll bundler
        bundle install && bundle exec jekyll build

    - name: Install Pa11y
      run: npm install -g pa11y

    - name: Run accessibility tests
      run: |
        pa11y ./_site/index.html
        pa11y --config ./scripts/config/mobile.json ./_site/index.html
        pa11y --config ./scripts/config/high-contrast.json ./_site/index.html
